# more info here about TravisCI and Java projects
# http://docs.travis-ci.com/user/languages/java/

language: java

jdk:
  - oraclejdk8
  
install: mvn clean install -q -DskipTests=true

cache:
  directories:
  - $HOME/.m2

script: mvn test -q